#!/bin/bash

mkdir -p build
echo "mkdir -p build"

g++ src/main.cpp src/helper.cpp src/mainloop.cpp src/simulation.cpp glad/src/glad.c -Iinclude -Iglad/include -Iglfw/include -Iglm -Lglfw/lib-mingw -lglfw3 -lopengl32 -lgdi32 -o build/app.exe

if [ $? -eq 0 ]; then
    echo "build done."
else
    echo "build failed."
    exit 1
fi
